import { Link } from '@tanstack/react-router';
import { ArrowLeft, House, Trophy, Medal, UserRound, Settings, Star, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { characters, useRajin } from '@/lib/rajin-state';
import type { ReactNode } from 'react';

export function Avatar({ character = 0, size = 'normal' }: { character?: number; size?: 'normal' | 'large' | 'small' }) { const person = characters[character] ?? characters[0]; return <span className={`kid-avatar ${person.tone} ${size}`}><img src={person.image} alt={`Karakter ${person.name}`} width={1024} height={1024} loading="lazy" /></span>; }
export function Stars({ count = 5 }: { count?: number }) { return <span className="stars" aria-label={`${count} bintang`}>{Array.from({ length: count }, (_, i) => <Star key={i} size={18} fill="currentColor" />)}</span>; }
export function ProgressBar({ value }: { value: number }) { return <div className="progress-track" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${Math.min(value, 100)}%` }} /></div>; }
export function BottomNav({ active }: { active: string }) { return <nav className="bottom-nav" aria-label="Navigasi utama">{[{ path: '/beranda' as const, label: 'Beranda', icon: House }, { path: '/challenge' as const, label: 'Challenge', icon: Trophy }, { path: '/koleksi' as const, label: 'Koleksi', icon: Medal }, { path: '/orang-tua' as const, label: 'Mama', icon: UserRound }].map(({ path, label, icon: Icon }) => <Link key={path} to={path} className={`nav-item ${active === label ? 'selected' : ''}`}><Icon size={22} strokeWidth={active === label ? 2.6 : 1.7} /><span>{label}</span></Link>)}</nav>; }
export function Page({ children, title, back = '/beranda', active, action }: { children: ReactNode; title: string; back?: '/beranda' | '/orang-tua' | '/challenge' | '/'; active?: string; action?: ReactNode }) { return <main className={`app-page ${active ? 'with-nav' : ''}`}><header className="page-header"><Button variant="softIcon" size="icon" asChild><Link to={back} aria-label="Kembali"><ArrowLeft size={20} /></Link></Button><h1>{title}</h1>{action ?? <span className="header-spacer" />}</header><div className="page-content">{children}</div>{active && <BottomNav active={active} />}</main>; }
export function SettingLink() { return <Button variant="softIcon" size="icon" asChild><Link to="/pengaturan" aria-label="Pengaturan"><Settings size={21} /></Link></Button>; }
export function KidRow({ index }: { index: number }) { const state = useRajin(); const kid = state.children[index]; if (!kid) return null; const pct = Math.round(kid.stars / 35 * 100); return <Link to="/progress" onClick={() => state.setActiveChild(index)} className="kid-row"><Avatar character={kid.character} /><div className="kid-row-info"><strong>{kid.name}</strong><div className="kid-row-progress"><span><Star size={14} fill="currentColor" /> {kid.stars} / 35</span><ProgressBar value={pct} /><small>{pct}%</small></div></div><ChevronRight size={18} /></Link>; }
export function Encouragement({ children }: { children: ReactNode }) { return <div className="encouragement"><Star size={21} fill="currentColor" /><span>{children}</span></div>; }
